language: go

go:
  - 1.5

env:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=linux GIMME_ARCH=386
    - GIMME_OS=darwin GIMME_ARCH=amd64
    - GIMME_OS=darwin GIMME_ARCH=386
    - GIMME_OS=windows GIMME_ARCH=amd64
    - GIMME_OS=windows GIMME_ARCH=386
    - GIMME_OS=freebsd GIMME_ARCH=amd64
    - GIMME_OS=freebsd GIMME_ARCH=386
